### ISSUE TITLE
Quran Flutter Package

### ISSUE THREAD

**Issue by aqeelshamz** [SadaqaWorks/Quran-Flutter#15]
Assalamu alaikum,

Please checkout my Flutter package. I hope it helps.
https://pub.dev/packages/quran

**Comment by Sadmansamee** [comment]
wa alaikum salam, it seems to extremely helpful, do you have any plan to add more translations ?

**Comment by Sadmansamee** [comment]
and why dont you use sqlite or json file instead of hardcoding?
