### ISSUE TITLE
ERROR: [TAG] Failed to resolve variable '${junit.version}'              

### ISSUE THREAD

**Issue by AhmadShakerASH** [SadaqaWorks/Quran-Flutter#19]
Launching lib/main.dart on Android SDK built for x86 in debug mode...
ERROR: [TAG] Failed to resolve variable '${junit.version}'              
ERROR: [TAG] Failed to resolve variable '${animal.sniffer.version}'

**Comment by Sadmansamee** [comment]
@AhmadShakerASH Merge with latest change
