### ISSUE TITLE
'onCreate' overrides nothing

### ISSUE THREAD

**Issue by AhmadShakerASH** [SadaqaWorks/Quran-Flutter#20]
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (10, 5): 'onCreate' overrides nothing
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (10, 47): Unresolved reference: Bundle
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (14, 13): Unresolved reference: Build
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (14, 38): Unresolved reference: Build
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (20, 19): Unresolved reference: flutterView
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (23, 13): Unresolved reference: flutterView
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (25, 17): Unresolved reference: Build
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (25, 42): Unresolved reference: Build
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (33, 5): 'configureFlutterEngine' overrides nothing
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (33, 42): Unresolved reference: NonNull
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (33, 65): Unresolved reference: FlutterEngine
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (35, 9): Unresolved reference: MethodChannel
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (35, 67): Unresolved reference: CHANNEL
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (35, 99): Cannot infer a type for this parameter. Please specify it explicitly.
e: /Users/ahmadshaker/Startups/Quran-master/android/app/src/main/kotlin/com/quran/universal/MainActivity.kt: (35, 105): Cannot infer a type for this parameter. Please specify it explicitly.

**Comment by ahmed951** [comment]
I also have the same error

**Comment by Sadmansamee** [comment]
@ahmed951 @AhmadShakerASH merge with latest changes, it has been fixed.
